version: "3.8"
services:
    web:
        container_name: wishflix-web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - '.:/app'
            - '/app/node_modules'